#!/bin/bash

TASKCOUNT=${TASKCOUNT-1}

MARATHON=`./marathon url`
if [ -z "$MARATHON" ]; then
  echo "no marathon detected" >&2
  exit 1
fi

APP_URL="$MARATHON/v2/apps/peters-demo-app"

function json {
  echo "app instances=$1" >&2
  cat app.json | sed -e "s/_instances_/$1/"
}

function start {
  # echo "start $1" >&2
  for a in $(seq 1 $TASKCOUNT); do
    json $1 | http PUT $APP_URL$a?force=true
  done
}

function stop {
  for a in $(seq 1 $TASKCOUNT); do
    http DELETE $APP_URL$a?force=true
  done
}

function scale {
  for a in $(seq 1 $TASKCOUNT); do
    echo "{ \"scaleBy\": $1 }"| http PUT $APP_URL$a
  done
}

function status {
  for a in $(seq 1 $TASKCOUNT); do
    http GET $APP_URL$a
  done
}

case "$1" in
  json)
    json ${2-2}
    ;;

	start)
    start ${2-2}
		;;
	stop)
    stop
		;;
	scale)
    scale ${2-2}
		;;
  status)
    status
    ;;
	*)
		echo "Usage: $0 start|stop|scale|json"
		;;
esac
  
